(function(){
    function createMap(){
        //map options
        let minZoom = 15,
            maxZoom = 17,
            bounds = ([
                [43.0669, -89.4634],
                [43.0943, -89.3885]
            ]);
        //map object
        let map = L.map('map', {
            minZoom:minZoom,
            maxZoom:maxZoom,
            maxBounds:bounds
        }).setView([43.075, -89.40], 16);
        //basemap tilelayer
        let baseLayer = L.tileLayer('data/basemap_test/{z}/{x}/{y}.jpg', {
            minZoom:minZoom,
            maxZoom:maxZoom,
            maxBounds:bounds,       
            attribution: 'Generated by QTiles',   
        }).addTo(map);     

        addSiteData(map);
    }
    //function to add sites to the map
    function addSiteData(map){
        //get site data
        fetch('data/sites.geojson')
            .then(res => res.json())
            .then(data => {
                let siteLayer = L.geoJson(data, {
                    onEachFeature:function(feature, layer){
                        //open story when layer is selected
                        layer.on('click',function(){
                            createSiteStory(feature)
                        })
                    }
                }).addTo(map);
            })
    }
    //function that populates the story 
    function createSiteStory(feature){
        //access modal element and retrieve content
        let storyElem = document.getElementById('story-modal'),
            storyModal = new bootstrap.Modal(storyElem),
            storyContent = document.querySelector('#story-content');    
        //clear story element content block
        storyContent.innerHTML = "";
        //update header
        document.querySelector('#story-title').innerHTML = "<h1>" + feature.properties.name + "</h1>";
        //add content from site to content block
        feature.properties.story.forEach(function(block){
            //create story block div
            var div = document.createElement("div");
            div.classList.add("story-block");
            //add content blocks if they exist
            //title
            if (block.title)
                div.insertAdjacentHTML('beforeend', "<h1>" + block.title + "</h1>")
            //image
            if (block.image)
                div.insertAdjacentHTML('beforeend', "<img src='" + block.image + "'>")
            //video
            if (block.video)
                div.insertAdjacentHTML('beforeend', "<iframe src='" + block.video + "'></iframe>")
            //paragraph
            if (block.content)
                div.insertAdjacentHTML('beforeend', "<p>" + block.content + "</p>")
            //insert story block into modal
            storyContent.insertAdjacentElement("beforeend", div)
        })

        //show modal
        storyModal.show();
    }
    //function runs when page is finished loading
    window.addEventListener('DOMContentLoaded',(event) => {
        createMap();
    });

})();
